### ISSUE TITLE
[Feature Request] Shipping pre-built binary & Real-time preview

### ISSUE THREAD

**Issue by slanterns** [Enter-tainer/typst-preview-vscode#1]
1. Since not everyone has a Rust toolchain, it will be good to ship a pre-built `typst-ws` binary like what `rust-analyzer` or `CodeLLDB` does;
2. Currently the rendering result will only be refreshed after saving, which is counter-intuitive. It will be better to work like those Markdown previewers that sync the content immediately.

**Comment by Enter-tainer** [comment]
For 1, it is needed to set up ci in https://github.com/Enter-tainer/typst-ws . And download the latest(?) artifact in this extension.

For 2, currently typst-ws works by listening to fs events (which is the same as the official 'typst watch'). I'm not sure how to port the "preview on type" style to this for now.

**Comment by Enter-tainer** [comment]
Seems that [rust-analyzer](https://github.com/rust-lang/rust-analyzer/blob/master/editors/code/src/bootstrap.ts#L34) ships binary within its vsix bundle. We may also follow the clangd approach, by downloading the latest artifact from github. I'm not sure how to distribute vsix bundle for different platforms. Maybe the clangd one is easier.

**Comment by Enter-tainer** [comment]
2 is done, by writing unsaved changes to a temp file.

**Comment by Enter-tainer** [comment]
- https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions
- https://github.com/nvarner/typst-lsp/blob/master/.github/workflows/release.yml
