### ISSUE TITLE
set RUST_BACKTRACE=1 for subprocess

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Enter-tainer/typst-preview-vscode#21]
When encounting a panic, the call stack is not currently being dumped. 

```
panic: src/main.rs:129
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace. 
```

We can set RUST_BACKTRACE=1 to get the backtrace. Additional information can be attached to provide more context, such as the version and commit hash of the subprocess. You can use [vergen](https://docs.rs/vergen/latest/vergen/) for integrating these information.

```shell
Build Timestamp:     2021-02-23T20:14:46.558472672+00:00
Describe:            0.1.0-9-g46f83e1
Commit SHA:          46f83e112520533338245862d366f6a02cef07d4
Commit Date:         2021-02-23T08:08:02-05:00
Commit Branch:       master
rustc Version:       1.52.0-nightly
rustc Channel:       nightly
rustc Host Triple:   x86_64-unknown-linux-gnu
rustc Commit SHA:    3f5aee2d5241139d808f4fdece0026603489afd1
cargo Target Triple: x86_64-unknown-linux-musl
cargo Profile:       release
```

**Comment by Enter-tainer** [comment]
in current implementation, panic may happen when current visible page no longer exists.

**Comment by Enter-tainer** [comment]
vergen is not added currently
