### ISSUE TITLE
Preview unable to update onType for included files

### ISSUE THREAD

**Issue by jac0b-w** [Enter-tainer/typst-preview-vscode#24]
It seems the preview is only able to update onType when I modify the `main.typ` file but if I include a file using `#include "file.typ"` it doesn't seem to able to update the preview when typing in `file.typ`.

**Comment by Enter-tainer** [comment]
Maybe we need to maintain all relevant files in memory? Not sure about how to fix this.

**Comment by Myriad-Dreamin** [comment]
All the source files in the editor must be watched and maintained by the previewer.

**Comment by Enter-tainer** [comment]
It has been implemented in v0.6.2. The new version will be available on vscode marketplace hopefully within 30mins. Please upgrade v0.6.2 and have a try!
