### ISSUE TITLE
Extension clears environment before launching typst-ws process

### ISSUE THREAD

**Issue by tadeokondrak** [Enter-tainer/typst-preview-vscode#33]
This code, as far as I understand, clears the environment entirely when launching the typst-ws process. On my setup, using [nix-ld] on NixOS, I need an environment variable to be passed through for the program to launch at all. Is it necessary to clear the environment here? 

https://github.com/Enter-tainer/typst-preview-vscode/blob/6e7dc5d61a3940847ac406de4304cbaeb60aba49/addons/vscode/src/extension.ts#L79-L84

[nix-ld]: https://github.com/Mic92/nix-ld

**Comment by Enter-tainer** [comment]
> This code, as far as I understand, clears the environment entirely

Oh I didn't aware of that! I just want to append RUST_BACKTRACE=1 to env vars.

Can you help me fix this?

**Comment by Enter-tainer** [comment]
BTW, as for nixos, rust analyzer seems to have some special code to patch binary shipped with vsix bundle. We may also follow the similar approach.
