### ISSUE TITLE
Jump to cursor, Code <--> PDF

### ISSUE THREAD

**Issue by KronosTheLate** [Enter-tainer/typst-preview-vscode#36]
It would be awesome to be able to press the preview and jump to the relevant code, or to press a button in the preview pane to jump to where the cursor is in code in the PDF. This is implemented in the online app.

**Comment by Myriad-Dreamin** [comment]
This requires cooperation between the LSP and the preview feature. Until the LSP exposes some of its functionality, it may not be achieved in a graceful way.

**Comment by Enter-tainer** [comment]
The cross jump between code and preview just landed in v0.5.1 (with bugs)

**Comment by KronosTheLate** [comment]
> The cross jump between code and preview just landed in v0.5.1 (with bugs)

Awesome! So that closes this issue then? I will close it, let me know if it should stay open for any reason.

**Comment by Enter-tainer** [comment]
Let's track bugs about cross jump in new issues(like #46) 🚀
