### ISSUE TITLE
preview to source jump not working after inserting new text in the source file

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typst-preview-vscode#46]
![image](https://github.com/Enter-tainer/typst-preview-vscode/assets/25521218/412a8927-3f51-4866-821b-48eb56426e2b)

**Comment by taooceros** [comment]
Adding a new theorem to the document by adding `#theorem[]` will reproduce this issue

[typstpreviewerror.zip](https://github.com/Enter-tainer/typst-preview-vscode/files/11929247/typstpreviewerror.zip)
