### ISSUE TITLE
[Bug] layout thrashing

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Enter-tainer/typst-preview-vscode#8]
### Bug Description

When typing, the pages in preview run away and sometimes it crashes the subprocess `typst-ws`.

### Possible root cause

Possibly a concurrency bug, caused by inconsistency between typing and updating document.

### Possible mitigations/solutions

+ utilize [OutputChannel](https://stackoverflow.com/questions/34085330/how-to-write-to-log-from-vscode-extension) to check what happened in `typst-ws`.
  
  ```typescript
      //Create output channel
    let orange = vscode.window.createOutputChannel("Orange");

    //Write to output.
    orange.appendLine("I am a banana.");
    ```
+ add an extension setting [preview.(onSave/onType/never)](https://github.com/nvarner/typst-lsp/blob/387e3f3e1d62469b2e29c8b9a0c81a9c65de165f/addons/vscode/package.json#L28-L32), which would help user disable features or debug the behaviors of this extension.
  
  ```json
  {
      "typst-lsp.exportPdf": {
          "title": "Export PDF",
          "description": "The extension can export PDFs of your Typst files. This setting controls whether this feature is enabled and how often it runs.",
          "type": "string",
          "default": "onSave",
          "enum": [
              "never",
              "onSave",
              "onType"
          ],
          "enumDescriptions": [
              "Never export PDFs, you will manually run typst.",
              "Export PDFs when you save a file.",
              "Export PDFs as you type in a file."
          ]
      }
  }
    ```

**Comment by Az-21** [comment]
Hi, I was looking for an option to update the preview `on save` instead of `on type`.

This issue is marked as closed, was this feature added?  I'm using `v0.1.10` of this extension and I can't find this setting.

Thanks for your help (and this extremely useful extension).

**Comment by Enter-tainer** [comment]
It's not added now, but will be added in future. 

This issue is closed because of an outdated version of typst-ws is used. But many useful features proposed in this issue are not fully implemented currently.

**Comment by Enter-tainer** [comment]
Added in #12, and it will appear in v0.2.2. Note that it may take some time(<15min) before v0.2.2 appear in the vscode marketplace
